### ISSUE TITLE
bug: wrong benchmark search

### ISSUE THREAD

**Issue by Chronostasys** [tidwall/btree-benchmark#2]
Hi, there seems to be a bug in the benchmark code. 
I'm recently learning btree and found your implementation. I'm really curious about the data in the benchmark section, which shows a remarkable speed in random read action. AFAIK, a btree's random read operation shall be significantly slower than sequencial reading. 
So I cloned this repo and tried it myself.  
And I found all search results in the benchmark code is `nil`!  You could add some code to check it like follow:  
```golang
	lotsa.Ops(N, 1, func(i, _ int) {
		re := tr.Get(&keys[i])
		if re == nil {
			panic(re)
		}
	})
```  
This bug means that previous benchmark result for `get` might be wrong.

**Comment by Chronostasys** [comment]
https://github.com/tidwall/btree-benchmark/blob/768381edcc4d628e4dc14d34688abab1f84b81db/main.go#L26

Seems this line is causing the trouble. As `keys` is an array of struct, passing it's pointer to `Set` followed by `shuffleInts` messed up the data in btrees.  
Changing it to array of pointers may solve this issue.

**Comment by tidwall** [comment]
Oh my, you're right. 

I corrected the benchmarks to use interfaces to the actual int values. Instead of using pointers. 
The numbers look much better now.

Thanks for reporting!
